{{- if .Values.keystone.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tpt-soma.fullname" . }}-keystone-secrets
  labels:
    {{- include "tpt-soma.labels" . | nindent 4 }}
type: Opaque
stringData:
  bootstrap-user: {{ .Values.keystone.auth.bootstrapUser | quote }}
  bootstrap-password: {{ .Values.keystone.auth.bootstrapPassword | quote }}
{{- end }}
