apiVersion: v2
name: tpt-soma
description: tpt-soma multi-scale computational physiology platform
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: "16.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keystone.enabled
  - name: minio
    version: "5.x"
    repository: "https://charts.min.io/"
    condition: minio.enabled
